import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ slug: string }> }
): Promise<NextResponse> {
  const { slug } = await params;

  try {
    const site = await prisma.websiteSubmission.findUnique({
      where: { slug }
    });

    if (!site) {
      return new NextResponse('Site Not Found', { status: 404 });
    }

    if (site.generatedHtml) {
      // Serve the raw HTML string exactly as generated by the AI
      // This bypasses Next.js React layouts completely, avoiding hydration errors
      return new NextResponse(site.generatedHtml, {
        headers: {
          'Content-Type': 'text/html; charset=utf-8',
          // Optional: Add cache control headers if you want edge caching
          'Cache-Control': 's-maxage=60, stale-while-revalidate=300',
        },
      });
    }

    // If the site exists but has no HTML generated yet, 
    // redirect them to the preview page to generate it.
    const baseUrl = new URL(req.url).origin;
    return NextResponse.redirect(`${baseUrl}/preview/${site.previewId}`);

  } catch (error) {
    console.error('[PROSERVICE] Error serving live site:', error);
    return new NextResponse('Internal Server Error', { status: 500 });
  }
}
